server:
  port: ${PORT:8080}
  forward-headers-strategy: native

spring:
  application:
    name: main-server

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:db.yml
      - classpath:maechuri.yml
      - classpath:minio.yml
      - classpath:api-limit.yml

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    dev.yunseong.apilimitwebflux: DEBUG